### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Czino**
Please ACK the addition of the MIT license

- [x] @lukaszsamson 
- [x] @soulexporter 
- [x] @vindard 
- [x] @Czino

### CODE REVIEW

**Comment by Czino** [comment]
Obviously, I ACK this change

**Review by soulexporter — APPROVED** [review]
A OK!

**Comment by lukaszsamson** [comment]
ACK

**Comment by vindard** [comment]
Ack

**Pull request merged**
